//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Group_Master
    {
        public int Group_Code { get; set; }
        public string Alias { get; set; }
        public string Group_Name { get; set; }
        public string Group_Type { get; set; }
        public Nullable<int> Group_TypeCode { get; set; }
        public Nullable<int> Parent_Code { get; set; }
        public string Parent_Name { get; set; }
        public string Schedule_Name { get; set; }
        public Nullable<int> Schedule_Code { get; set; }
        public Nullable<int> Schedule_No { get; set; }
        public string Schedule_Type { get; set; }
        public Nullable<bool> Reserve { get; set; }
        public Nullable<decimal> PrevYear { get; set; }
        public string Top_Group { get; set; }
        public Nullable<int> Top_Group_Code { get; set; }
        public string Sub_Led { get; set; }
        public Nullable<decimal> Op_Bal { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> OpDr { get; set; }
        public Nullable<decimal> OpCr { get; set; }
        public Nullable<decimal> Dr01 { get; set; }
        public Nullable<decimal> Cr01 { get; set; }
        public Nullable<decimal> Dr02 { get; set; }
        public Nullable<decimal> Cr02 { get; set; }
        public Nullable<decimal> Dr03 { get; set; }
        public Nullable<decimal> Cr03 { get; set; }
        public Nullable<decimal> Dr04 { get; set; }
        public Nullable<decimal> Cr04 { get; set; }
        public Nullable<decimal> Dr05 { get; set; }
        public Nullable<decimal> Cr05 { get; set; }
        public Nullable<decimal> Dr06 { get; set; }
        public Nullable<decimal> Cr06 { get; set; }
        public Nullable<decimal> Dr07 { get; set; }
        public Nullable<decimal> Cr07 { get; set; }
        public Nullable<decimal> Dr08 { get; set; }
        public Nullable<decimal> Cr08 { get; set; }
        public Nullable<decimal> Dr09 { get; set; }
        public Nullable<decimal> Cr09 { get; set; }
        public Nullable<decimal> Dr10 { get; set; }
        public Nullable<decimal> Cr10 { get; set; }
        public Nullable<decimal> Dr11 { get; set; }
        public Nullable<decimal> Cr11 { get; set; }
        public Nullable<decimal> Dr12 { get; set; }
        public Nullable<decimal> Cr12 { get; set; }
        public Nullable<decimal> BalDr { get; set; }
        public Nullable<decimal> BalCr { get; set; }
    }
}
