//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID { get; set; }
        public Nullable<int> AgentMobile { get; set; }
        public string AgenteMail { get; set; }
        public Nullable<int> CustMobile { get; set; }
        public string CusteMail { get; set; }
        public string Attch1 { get; set; }
        public string Attch2 { get; set; }
        public string Attch3 { get; set; }
        public string IpAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> CurDate { get; set; }
        public byte[] Doc1 { get; set; }
        public byte[] Doc2 { get; set; }
        public byte[] Doc3 { get; set; }
    }
}
