//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Activation
    {
        public int Srno { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_gstno { get; set; }
        public Nullable<System.DateTime> active_till { get; set; }
        public string Active { get; set; }
        public string Order_Active { get; set; }
        public bool Approved { get; set; }
        public int ID { get; set; }
    }
}
