//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int Id { get; set; }
        public string UserType { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoUrl { get; set; }
        public string Mobile { get; set; }
        public string eMail { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string City { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public string Country { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Validate { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string VerifyCode { get; set; }
        public Nullable<bool> eMailFlg { get; set; }
        public Nullable<bool> AppFlg { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string IpAddress { get; set; }
        public string MacAddress { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
