//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstDistrict
    {
        public decimal Dist_Code { get; set; }
        public string Dist_Name { get; set; }
        public decimal State_Code { get; set; }
        public bool Active { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
