//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstUser
    {
        public int ID { get; set; }
        public string Party { get; set; }
        public string Mobile { get; set; }
        public string Agent { get; set; }
        public string AgentMobile { get; set; }
        public string Salesman { get; set; }
        public string SalesmanMobile { get; set; }
        public string AcofName { get; set; }
        public string AcofMobile { get; set; }
        public string Comp_Name { get; set; }
        public string CompMobile { get; set; }
        public string Comp_GstNo { get; set; }
        public string UserTyp { get; set; }
    }
}
