//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item_trans
    {
        public int srno { get; set; }
        public string order_cancel { get; set; }
        public Nullable<int> orderno { get; set; }
        public string cut { get; set; }
        public string item { get; set; }
        public string desno { get; set; }
        public string shade { get; set; }
        public string unit { get; set; }
        public string pcs { get; set; }
        public string qty { get; set; }
        public string Comp_Gstno { get; set; }
        public string itemno { get; set; }
    }
}
