//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMst
    {
        public Nullable<int> orderno { get; set; }
        public string order_cancel { get; set; }
        public string UserName { get; set; }
        public string party { get; set; }
        public string party_code { get; set; }
        public string shipto { get; set; }
        public string orderDate { get; set; }
        public string shipto_code { get; set; }
        public string transport { get; set; }
        public string transport_code { get; set; }
        public string despatch { get; set; }
        public string packing_code { get; set; }
        public string retailer { get; set; }
        public string sample_code { get; set; }
        public string packing { get; set; }
        public string gift_code { get; set; }
        public string sample { get; set; }
        public string gift { get; set; }
        public string remark { get; set; }
        public string Comp_Gstno { get; set; }
        public int Srno { get; set; }
        public string AgentMobile { get; set; }
        public string Mobile { get; set; }
        public string CompMobile { get; set; }
        public string salesmanMobile { get; set; }
        public string Comp_Name { get; set; }
    }
}
