//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int ID { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_GstNo { get; set; }
        public string Mobile { get; set; }
        public string AgentMobile { get; set; }
        public string Party { get; set; }
        public string Agent { get; set; }
        public string Acof { get; set; }
        public string Retailer { get; set; }
        public string Transport { get; set; }
        public string Despatch { get; set; }
        public string Ord_No { get; set; }
        public Nullable<System.DateTime> Ord_Date { get; set; }
        public string Item { get; set; }
        public string Shade { get; set; }
        public string Des_No { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> NoPcs { get; set; }
        public Nullable<decimal> DespQty { get; set; }
        public Nullable<decimal> PendQty { get; set; }
        public string CompMobile { get; set; }
        public Nullable<int> Vno { get; set; }
        public Nullable<int> Book_Code { get; set; }
        public string Fvno { get; set; }
        public string fld_read { get; set; }
        public string agent_fld_read { get; set; }
        public string Comp_fldread { get; set; }
        public string AcofMobile { get; set; }
    }
}
