//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class outstandingInfo
    {
        public int ID { get; set; }
        public string agentfld_READ { get; set; }
        public string compfld_READ { get; set; }
        public string gstno { get; set; }
        public string AgentMobile { get; set; }
        public string Mobile { get; set; }
        public string AgentName { get; set; }
        public string Party { get; set; }
        public Nullable<System.DateTime> Bill_date { get; set; }
        public string Bill_No { get; set; }
        public Nullable<decimal> Bill_Amt { get; set; }
        public Nullable<decimal> Due_Amt { get; set; }
        public Nullable<int> fld_READ { get; set; }
        public string Comp_Name { get; set; }
        public string CompMobile { get; set; }
        public string Comp_GstNo { get; set; }
    }
}
