//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackInfo
    {
        public int ID { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_GstNo { get; set; }
        public string CompMobile { get; set; }
        public string Mobile { get; set; }
        public string AgMobile { get; set; }
        public string Party { get; set; }
        public string Agent { get; set; }
        public string account_name { get; set; }
        public string Retailer { get; set; }
        public string Trans_Name { get; set; }
        public string Despatch { get; set; }
        public string Ord_No { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string Caseno { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Item_Name { get; set; }
        public string Shade { get; set; }
        public string Des_No { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<int> No_Pcs { get; set; }
        public string FVno { get; set; }
        public Nullable<int> Vno { get; set; }
        public Nullable<int> Book_Code { get; set; }
        public string AcofMobile { get; set; }
    }
}
