//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms_TransNew1
    {
        public int ID { get; set; }
        public string Comp_GSTno { get; set; }
        public Nullable<int> VNo { get; set; }
        public Nullable<int> Book_Code { get; set; }
        public string Book_Short { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Party_Code { get; set; }
        public Nullable<int> Acof_Code { get; set; }
        public Nullable<int> Agent_Code { get; set; }
        public Nullable<int> Sr_No { get; set; }
       public string Caseno { get; set; }
        public string Des_No { get; set; }
        public string Shade { get; set; }
        public string Item { get; set; }
        public Nullable<int> Item_Code { get; set; }
        public string Unit { get; set; }
        public string Remark { get; set; }
        public Nullable<int> No_Pcs { get; set; }
        public Nullable<int> Cases { get; set; }
        public string Cut { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Desc { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Bill_No { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public string Ord_No { get; set; }
        public Nullable<System.DateTime> AcDate { get; set; }
        public string chl_no { get; set; }
        public string shade_no { get; set; }
        public string FVno { get; set; }
        public Nullable<int> Book_Ac_Code { get; set; }
        public string GSTNO { get; set; }
        public string CompMobile { get; set; }
        public string AcofName { get; set; }
        public string AcofMobile { get; set; }
    }
}
