//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms_TransNew
    {
        public int ID { get; set; }
        public string agentfld_READ { get; set; }
        public string compfld_READ { get; set; }
        public string fld_READ { get; set; }
        public string fld_GROUP { get; set; }
        public string Comp_GSTno { get; set; }
        public Nullable<decimal> Comp_Code { get; set; }
        public string Comp_Name { get; set; }
        public string CompMobile { get; set; }
        public string CompMail { get; set; }
        public string Book { get; set; }
        public string Fvno { get; set; }
        public string Agent { get; set; }
        public string AgentMobile { get; set; }
        public string AgentEmail { get; set; }
        public string Party { get; set; }
        public string Supplier { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
        public string Acof_Name { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string Ord_No { get; set; }
        public Nullable<System.DateTime> Bill_date { get; set; }
        public string CaseNo { get; set; }
        public string Bill_No { get; set; }
        public string Lrno { get; set; }
        public Nullable<System.DateTime> Lrdate { get; set; }
        public string Transport { get; set; }
        public string Despatch { get; set; }
        public string Item { get; set; }
        public string Shade { get; set; }
        public string Des_No { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AddLess { get; set; }
        public Nullable<decimal> ROff_Amt { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public byte[] Invoice { get; set; }
        public byte[] PackingSlip { get; set; }
        public Nullable<int> Vno { get; set; }
        public Nullable<int> Book_Code { get; set; }
        public string salesmanMobile { get; set; }
        public string AcofMobile { get; set; }
    }
}
